#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop aesdsocket daemon
# Description:       Start and stop aesdsocket application daemon
### END INIT INFO

DESC="aesdsocket daemon"
NAME=aesdsocket
DAEMON=/usr/bin/aesdsocket
PIDFILE=/var/run/aesdsocket.pid

case "$1" in
    start)
        printf "Starting $DESC: "
        start-stop-daemon --start --quiet --pidfile $PIDFILE \
            --exec $DAEMON -- -d
        echo "$NAME."
        ;;
    stop)
        printf "Stopping $DESC: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
            --signal SIGTERM
        echo "$NAME."
        ;;
    restart)
        printf "Restarting $DESC: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
            --signal SIGTERM
        sleep 1
        start-stop-daemon --start --quiet --pidfile $PIDFILE \
            --exec $DAEMON -- -d
        echo "$NAME."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
